### ISSUE TITLE
Shorterned Links appear in google search

### ISSUE THREAD

**Issue by adithyapaib** [sumitkolhe/kut#4]
I used ur site to shorten my social media profile links  on my portfollio site 
Now the shortened link appear on google search 
(I think ur site links are seo friendly?)

**Comment by sumitkolhe** [comment]
Can you link those shortened urls here?

**Comment by adithyapaib** [comment]
https://reduced.me/adyl
https://www.google.com/search?q=adithya+pai+b&oq=adithya+pai+b&aqs=chrome.0.69i59j0l3j69i60l3.6507j0j7&sourceid=chrome&ie=UTF-8

**Comment by sumitkolhe** [comment]
I can't see any shortened links being listed on Google. Moreover all shortened links expire after 10 days by default so even if they are listed on Google they will be unlisted once they expire. I'm working on an option to set custom expiration dates. Should be available in the next update.

**Comment by adithyapaib** [comment]
https://ibb.co/4V8tdr0 
Check this ss

**Comment by sumitkolhe** [comment]
> all shortened links expire after 10 days by default so even if they are listed on Google they will be unlisted once they expire. I'm working on an option to set custom expiration dates. Should be available in the next update.

Please see this.

**Comment by adithyapaib** [comment]
Ohh Ok
